=begin comment

WhatsAPI Go

The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::BusinessManagementApi');

my $api = WWW::OpenAPIClient::BusinessManagementApi->new();
isa_ok($api, 'WWW::OpenAPIClient::BusinessManagementApi');

#
# instances_instance_key_business_catalog_get test
#
# uncomment below and update the test
#my $instances_instance_key_business_catalog_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_business_catalog_get_result = $api->instances_instance_key_business_catalog_get(instance_key => $instances_instance_key_business_catalog_get_instance_key);

