=begin comment

WhatsAPI Go

The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::GroupManagementApi');

my $api = WWW::OpenAPIClient::GroupManagementApi->new();
isa_ok($api, 'WWW::OpenAPIClient::GroupManagementApi');

#
# instances_instance_key_groups_admin_get test
#
# uncomment below and update the test
#my $instances_instance_key_groups_admin_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_admin_get_result = $api->instances_instance_key_groups_admin_get(instance_key => $instances_instance_key_groups_admin_get_instance_key);

#
# instances_instance_key_groups_create_post test
#
# uncomment below and update the test
#my $instances_instance_key_groups_create_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_create_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_create_post_result = $api->instances_instance_key_groups_create_post(instance_key => $instances_instance_key_groups_create_post_instance_key, data => $instances_instance_key_groups_create_post_data);

#
# instances_instance_key_groups_get test
#
# uncomment below and update the test
#my $instances_instance_key_groups_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_get_include_participants = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_get_result = $api->instances_instance_key_groups_get(instance_key => $instances_instance_key_groups_get_instance_key, include_participants => $instances_instance_key_groups_get_include_participants);

#
# instances_instance_key_groups_group_id_announce_put test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_announce_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_announce_put_announce = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_announce_put_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_announce_put_result = $api->instances_instance_key_groups_group_id_announce_put(instance_key => $instances_instance_key_groups_group_id_announce_put_instance_key, announce => $instances_instance_key_groups_group_id_announce_put_announce, group_id => $instances_instance_key_groups_group_id_announce_put_group_id);

#
# instances_instance_key_groups_group_id_delete test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_delete_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_delete_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_delete_result = $api->instances_instance_key_groups_group_id_delete(instance_key => $instances_instance_key_groups_group_id_delete_instance_key, group_id => $instances_instance_key_groups_group_id_delete_group_id);

#
# instances_instance_key_groups_group_id_description_put test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_description_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_description_put_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_description_put_data = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_description_put_result = $api->instances_instance_key_groups_group_id_description_put(instance_key => $instances_instance_key_groups_group_id_description_put_instance_key, group_id => $instances_instance_key_groups_group_id_description_put_group_id, data => $instances_instance_key_groups_group_id_description_put_data);

#
# instances_instance_key_groups_group_id_get test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_get_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_get_result = $api->instances_instance_key_groups_group_id_get(instance_key => $instances_instance_key_groups_group_id_get_instance_key, group_id => $instances_instance_key_groups_group_id_get_group_id);

#
# instances_instance_key_groups_group_id_invite_code_get test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_invite_code_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_invite_code_get_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_invite_code_get_result = $api->instances_instance_key_groups_group_id_invite_code_get(instance_key => $instances_instance_key_groups_group_id_invite_code_get_instance_key, group_id => $instances_instance_key_groups_group_id_invite_code_get_group_id);

#
# instances_instance_key_groups_group_id_lock_put test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_lock_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_lock_put_locked = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_lock_put_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_lock_put_result = $api->instances_instance_key_groups_group_id_lock_put(instance_key => $instances_instance_key_groups_group_id_lock_put_instance_key, locked => $instances_instance_key_groups_group_id_lock_put_locked, group_id => $instances_instance_key_groups_group_id_lock_put_group_id);

#
# instances_instance_key_groups_group_id_name_put test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_name_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_name_put_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_name_put_data = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_name_put_result = $api->instances_instance_key_groups_group_id_name_put(instance_key => $instances_instance_key_groups_group_id_name_put_instance_key, group_id => $instances_instance_key_groups_group_id_name_put_group_id, data => $instances_instance_key_groups_group_id_name_put_data);

#
# instances_instance_key_groups_group_id_participants_add_post test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_participants_add_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_add_post_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_add_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_add_post_result = $api->instances_instance_key_groups_group_id_participants_add_post(instance_key => $instances_instance_key_groups_group_id_participants_add_post_instance_key, group_id => $instances_instance_key_groups_group_id_participants_add_post_group_id, data => $instances_instance_key_groups_group_id_participants_add_post_data);

#
# instances_instance_key_groups_group_id_participants_demote_put test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_participants_demote_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_demote_put_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_demote_put_data = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_demote_put_result = $api->instances_instance_key_groups_group_id_participants_demote_put(instance_key => $instances_instance_key_groups_group_id_participants_demote_put_instance_key, group_id => $instances_instance_key_groups_group_id_participants_demote_put_group_id, data => $instances_instance_key_groups_group_id_participants_demote_put_data);

#
# instances_instance_key_groups_group_id_participants_promote_put test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_participants_promote_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_promote_put_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_promote_put_data = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_promote_put_result = $api->instances_instance_key_groups_group_id_participants_promote_put(instance_key => $instances_instance_key_groups_group_id_participants_promote_put_instance_key, group_id => $instances_instance_key_groups_group_id_participants_promote_put_group_id, data => $instances_instance_key_groups_group_id_participants_promote_put_data);

#
# instances_instance_key_groups_group_id_participants_remove_delete test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_participants_remove_delete_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_remove_delete_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_remove_delete_data = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_participants_remove_delete_result = $api->instances_instance_key_groups_group_id_participants_remove_delete(instance_key => $instances_instance_key_groups_group_id_participants_remove_delete_instance_key, group_id => $instances_instance_key_groups_group_id_participants_remove_delete_group_id, data => $instances_instance_key_groups_group_id_participants_remove_delete_data);

#
# instances_instance_key_groups_group_id_profile_pic_put test
#
# uncomment below and update the test
#my $instances_instance_key_groups_group_id_profile_pic_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_profile_pic_put_group_id = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_profile_pic_put_instances_instance_key_groups_group_id_profile_pic_put_request = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_group_id_profile_pic_put_result = $api->instances_instance_key_groups_group_id_profile_pic_put(instance_key => $instances_instance_key_groups_group_id_profile_pic_put_instance_key, group_id => $instances_instance_key_groups_group_id_profile_pic_put_group_id, instances_instance_key_groups_group_id_profile_pic_put_request => $instances_instance_key_groups_group_id_profile_pic_put_instances_instance_key_groups_group_id_profile_pic_put_request);

#
# instances_instance_key_groups_invite_info_get test
#
# uncomment below and update the test
#my $instances_instance_key_groups_invite_info_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_invite_info_get_invite_link = undef; # replace NULL with a proper value
#my $instances_instance_key_groups_invite_info_get_result = $api->instances_instance_key_groups_invite_info_get(instance_key => $instances_instance_key_groups_invite_info_get_instance_key, invite_link => $instances_instance_key_groups_invite_info_get_invite_link);

