=begin comment

WhatsAPI Go

The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::InstanceApi');

my $api = WWW::OpenAPIClient::InstanceApi->new();
isa_ok($api, 'WWW::OpenAPIClient::InstanceApi');

#
# instances_create_get test
#
# uncomment below and update the test
#my $instances_create_get_instance_key = undef; # replace NULL with a proper value
#my $instances_create_get_result = $api->instances_create_get(instance_key => $instances_create_get_instance_key);

#
# instances_instance_key_contacts_get test
#
# uncomment below and update the test
#my $instances_instance_key_contacts_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_contacts_get_result = $api->instances_instance_key_contacts_get(instance_key => $instances_instance_key_contacts_get_instance_key);

#
# instances_instance_key_delete_delete test
#
# uncomment below and update the test
#my $instances_instance_key_delete_delete_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_delete_delete_result = $api->instances_instance_key_delete_delete(instance_key => $instances_instance_key_delete_delete_instance_key);

#
# instances_instance_key_get test
#
# uncomment below and update the test
#my $instances_instance_key_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_get_result = $api->instances_instance_key_get(instance_key => $instances_instance_key_get_instance_key);

#
# instances_instance_key_logout_delete test
#
# uncomment below and update the test
#my $instances_instance_key_logout_delete_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_logout_delete_result = $api->instances_instance_key_logout_delete(instance_key => $instances_instance_key_logout_delete_instance_key);

#
# instances_instance_key_qrcode_get test
#
# uncomment below and update the test
#my $instances_instance_key_qrcode_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_qrcode_get_result = $api->instances_instance_key_qrcode_get(instance_key => $instances_instance_key_qrcode_get_instance_key);

#
# instances_instance_key_webhook_put test
#
# uncomment below and update the test
#my $instances_instance_key_webhook_put_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_webhook_put_data = undef; # replace NULL with a proper value
#my $instances_instance_key_webhook_put_result = $api->instances_instance_key_webhook_put(instance_key => $instances_instance_key_webhook_put_instance_key, data => $instances_instance_key_webhook_put_data);

#
# instances_list_get test
#
# uncomment below and update the test
#my $instances_list_get_result = $api->instances_list_get();

