=begin comment

WhatsAPI Go

The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::MessageSendingApi');

my $api = WWW::OpenAPIClient::MessageSendingApi->new();
isa_ok($api, 'WWW::OpenAPIClient::MessageSendingApi');

#
# instances_instance_key_business_catalog_get test
#
# uncomment below and update the test
#my $instances_instance_key_business_catalog_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_business_catalog_get_result = $api->instances_instance_key_business_catalog_get(instance_key => $instances_instance_key_business_catalog_get_instance_key);

#
# instances_instance_key_send_audio_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_audio_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_audio_post_to = undef; # replace NULL with a proper value
#my $instances_instance_key_send_audio_post_instances_instance_key_send_audio_post_request = undef; # replace NULL with a proper value
#my $instances_instance_key_send_audio_post_caption = undef; # replace NULL with a proper value
#my $instances_instance_key_send_audio_post_result = $api->instances_instance_key_send_audio_post(instance_key => $instances_instance_key_send_audio_post_instance_key, to => $instances_instance_key_send_audio_post_to, instances_instance_key_send_audio_post_request => $instances_instance_key_send_audio_post_instances_instance_key_send_audio_post_request, caption => $instances_instance_key_send_audio_post_caption);

#
# instances_instance_key_send_button_media_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_button_media_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_button_media_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_button_media_post_result = $api->instances_instance_key_send_button_media_post(instance_key => $instances_instance_key_send_button_media_post_instance_key, data => $instances_instance_key_send_button_media_post_data);

#
# instances_instance_key_send_buttons_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_buttons_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_buttons_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_buttons_post_result = $api->instances_instance_key_send_buttons_post(instance_key => $instances_instance_key_send_buttons_post_instance_key, data => $instances_instance_key_send_buttons_post_data);

#
# instances_instance_key_send_contact_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_contact_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_contact_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_contact_post_result = $api->instances_instance_key_send_contact_post(instance_key => $instances_instance_key_send_contact_post_instance_key, data => $instances_instance_key_send_contact_post_data);

#
# instances_instance_key_send_document_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_document_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_document_post_to = undef; # replace NULL with a proper value
#my $instances_instance_key_send_document_post_instances_instance_key_send_document_post_request = undef; # replace NULL with a proper value
#my $instances_instance_key_send_document_post_caption = undef; # replace NULL with a proper value
#my $instances_instance_key_send_document_post_result = $api->instances_instance_key_send_document_post(instance_key => $instances_instance_key_send_document_post_instance_key, to => $instances_instance_key_send_document_post_to, instances_instance_key_send_document_post_request => $instances_instance_key_send_document_post_instances_instance_key_send_document_post_request, caption => $instances_instance_key_send_document_post_caption);

#
# instances_instance_key_send_image_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_image_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_image_post_to = undef; # replace NULL with a proper value
#my $instances_instance_key_send_image_post_instances_instance_key_send_image_post_request = undef; # replace NULL with a proper value
#my $instances_instance_key_send_image_post_caption = undef; # replace NULL with a proper value
#my $instances_instance_key_send_image_post_result = $api->instances_instance_key_send_image_post(instance_key => $instances_instance_key_send_image_post_instance_key, to => $instances_instance_key_send_image_post_to, instances_instance_key_send_image_post_request => $instances_instance_key_send_image_post_instances_instance_key_send_image_post_request, caption => $instances_instance_key_send_image_post_caption);

#
# instances_instance_key_send_list_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_list_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_list_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_list_post_result = $api->instances_instance_key_send_list_post(instance_key => $instances_instance_key_send_list_post_instance_key, data => $instances_instance_key_send_list_post_data);

#
# instances_instance_key_send_location_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_location_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_location_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_location_post_result = $api->instances_instance_key_send_location_post(instance_key => $instances_instance_key_send_location_post_instance_key, data => $instances_instance_key_send_location_post_data);

#
# instances_instance_key_send_media_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_media_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_media_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_media_post_result = $api->instances_instance_key_send_media_post(instance_key => $instances_instance_key_send_media_post_instance_key, data => $instances_instance_key_send_media_post_data);

#
# instances_instance_key_send_poll_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_poll_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_poll_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_poll_post_result = $api->instances_instance_key_send_poll_post(instance_key => $instances_instance_key_send_poll_post_instance_key, data => $instances_instance_key_send_poll_post_data);

#
# instances_instance_key_send_template_media_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_template_media_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_template_media_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_template_media_post_result = $api->instances_instance_key_send_template_media_post(instance_key => $instances_instance_key_send_template_media_post_instance_key, data => $instances_instance_key_send_template_media_post_data);

#
# instances_instance_key_send_template_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_template_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_template_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_template_post_result = $api->instances_instance_key_send_template_post(instance_key => $instances_instance_key_send_template_post_instance_key, data => $instances_instance_key_send_template_post_data);

#
# instances_instance_key_send_text_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_text_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_text_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_send_text_post_result = $api->instances_instance_key_send_text_post(instance_key => $instances_instance_key_send_text_post_instance_key, data => $instances_instance_key_send_text_post_data);

#
# instances_instance_key_send_upload_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_upload_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_upload_post_type = undef; # replace NULL with a proper value
#my $instances_instance_key_send_upload_post_instances_instance_key_send_upload_post_request = undef; # replace NULL with a proper value
#my $instances_instance_key_send_upload_post_result = $api->instances_instance_key_send_upload_post(instance_key => $instances_instance_key_send_upload_post_instance_key, type => $instances_instance_key_send_upload_post_type, instances_instance_key_send_upload_post_request => $instances_instance_key_send_upload_post_instances_instance_key_send_upload_post_request);

#
# instances_instance_key_send_video_post test
#
# uncomment below and update the test
#my $instances_instance_key_send_video_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_send_video_post_to = undef; # replace NULL with a proper value
#my $instances_instance_key_send_video_post_instances_instance_key_send_video_post_request = undef; # replace NULL with a proper value
#my $instances_instance_key_send_video_post_caption = undef; # replace NULL with a proper value
#my $instances_instance_key_send_video_post_result = $api->instances_instance_key_send_video_post(instance_key => $instances_instance_key_send_video_post_instance_key, to => $instances_instance_key_send_video_post_to, instances_instance_key_send_video_post_request => $instances_instance_key_send_video_post_instances_instance_key_send_video_post_request, caption => $instances_instance_key_send_video_post_caption);

