=begin comment

WhatsAPI Go

The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::MiscellaneousApi');

my $api = WWW::OpenAPIClient::MiscellaneousApi->new();
isa_ok($api, 'WWW::OpenAPIClient::MiscellaneousApi');

#
# instances_instance_key_misc_profile_pic_get test
#
# uncomment below and update the test
#my $instances_instance_key_misc_profile_pic_get_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_misc_profile_pic_get_jid = undef; # replace NULL with a proper value
#my $instances_instance_key_misc_profile_pic_get_result = $api->instances_instance_key_misc_profile_pic_get(instance_key => $instances_instance_key_misc_profile_pic_get_instance_key, jid => $instances_instance_key_misc_profile_pic_get_jid);

#
# instances_instance_key_misc_user_info_post test
#
# uncomment below and update the test
#my $instances_instance_key_misc_user_info_post_instance_key = undef; # replace NULL with a proper value
#my $instances_instance_key_misc_user_info_post_data = undef; # replace NULL with a proper value
#my $instances_instance_key_misc_user_info_post_result = $api->instances_instance_key_misc_user_info_post(instance_key => $instances_instance_key_misc_user_info_post_instance_key, data => $instances_instance_key_misc_user_info_post_data);

