=begin comment

WhatsAPI Go

The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 2;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('WWW::OpenAPIClient::Object::StructsContactMessagePayload');

# uncomment below and update the test
#my $instance = WWW::OpenAPIClient::Object::StructsContactMessagePayload->new();
#
#isa_ok($instance, 'WWW::OpenAPIClient::Object::StructsContactMessagePayload');

